### ISSUE TITLE
Enable delegate peer routing

### ISSUE THREAD

**Issue by oed** [3box/3box-js#604]
As described here: https://github.com/ipfs/js-ipfs/releases/tag/v0.37.0

Steps:
- [ ] Set up delegate routing node locally
- [ ] Add code for connecting to node
- [ ] Test that delegate routing works correctly
- [ ] Dockerize and deploy delegate routing node
- [ ] Connect to deployed node in 3box-js
- [ ] Further testing
